//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IDH.Sales.BLL.SalesRepWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SalesRepWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SalesRepWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSalesRepListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetManagerListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActivateDeactivateOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeactivateManagerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeamOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTeamManagersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SalesRepWebService() {
            this.Url = global::IDH.Sales.BLL.Properties.Settings.Default.IDH_Sales_BLL_SalesRepWebReference_SalesRepWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSalesRepListCompletedEventHandler GetSalesRepListCompleted;
        
        /// <remarks/>
        public event GetManagerListCompletedEventHandler GetManagerListCompleted;
        
        /// <remarks/>
        public event ActivateDeactivateCompletedEventHandler ActivateDeactivateCompleted;
        
        /// <remarks/>
        public event DeactivateManagerCompletedEventHandler DeactivateManagerCompleted;
        
        /// <remarks/>
        public event GetTeamCompletedEventHandler GetTeamCompleted;
        
        /// <remarks/>
        public event GetTeamManagersCompletedEventHandler GetTeamManagersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSalesRepList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKN_P_GetSalesRepList_Result[] GetSalesRepList(string _RoleID, string _UserID, int _CompanyID) {
            object[] results = this.Invoke("GetSalesRepList", new object[] {
                        _RoleID,
                        _UserID,
                        _CompanyID});
            return ((YKN_P_GetSalesRepList_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSalesRepListAsync(string _RoleID, string _UserID, int _CompanyID) {
            this.GetSalesRepListAsync(_RoleID, _UserID, _CompanyID, null);
        }
        
        /// <remarks/>
        public void GetSalesRepListAsync(string _RoleID, string _UserID, int _CompanyID, object userState) {
            if ((this.GetSalesRepListOperationCompleted == null)) {
                this.GetSalesRepListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSalesRepListOperationCompleted);
            }
            this.InvokeAsync("GetSalesRepList", new object[] {
                        _RoleID,
                        _UserID,
                        _CompanyID}, this.GetSalesRepListOperationCompleted, userState);
        }
        
        private void OnGetSalesRepListOperationCompleted(object arg) {
            if ((this.GetSalesRepListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSalesRepListCompleted(this, new GetSalesRepListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetManagerList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKN_P_GetManagerList_Result[] GetManagerList(int _CompanyID) {
            object[] results = this.Invoke("GetManagerList", new object[] {
                        _CompanyID});
            return ((YKN_P_GetManagerList_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void GetManagerListAsync(int _CompanyID) {
            this.GetManagerListAsync(_CompanyID, null);
        }
        
        /// <remarks/>
        public void GetManagerListAsync(int _CompanyID, object userState) {
            if ((this.GetManagerListOperationCompleted == null)) {
                this.GetManagerListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetManagerListOperationCompleted);
            }
            this.InvokeAsync("GetManagerList", new object[] {
                        _CompanyID}, this.GetManagerListOperationCompleted, userState);
        }
        
        private void OnGetManagerListOperationCompleted(object arg) {
            if ((this.GetManagerListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetManagerListCompleted(this, new GetManagerListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActivateDeactivate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActivateDeactivate(System.Guid _Guid, System.Guid _ManagerID, System.Guid _UserGuid, System.Guid _SalesRepID, int _StatusCode, int _CompanyID) {
            this.Invoke("ActivateDeactivate", new object[] {
                        _Guid,
                        _ManagerID,
                        _UserGuid,
                        _SalesRepID,
                        _StatusCode,
                        _CompanyID});
        }
        
        /// <remarks/>
        public void ActivateDeactivateAsync(System.Guid _Guid, System.Guid _ManagerID, System.Guid _UserGuid, System.Guid _SalesRepID, int _StatusCode, int _CompanyID) {
            this.ActivateDeactivateAsync(_Guid, _ManagerID, _UserGuid, _SalesRepID, _StatusCode, _CompanyID, null);
        }
        
        /// <remarks/>
        public void ActivateDeactivateAsync(System.Guid _Guid, System.Guid _ManagerID, System.Guid _UserGuid, System.Guid _SalesRepID, int _StatusCode, int _CompanyID, object userState) {
            if ((this.ActivateDeactivateOperationCompleted == null)) {
                this.ActivateDeactivateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActivateDeactivateOperationCompleted);
            }
            this.InvokeAsync("ActivateDeactivate", new object[] {
                        _Guid,
                        _ManagerID,
                        _UserGuid,
                        _SalesRepID,
                        _StatusCode,
                        _CompanyID}, this.ActivateDeactivateOperationCompleted, userState);
        }
        
        private void OnActivateDeactivateOperationCompleted(object arg) {
            if ((this.ActivateDeactivateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActivateDeactivateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeactivateManager", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeactivateManager(System.Guid _Guid, System.Guid _ManagerID, System.Guid _UserGuid, System.Guid _AlternateManagerID, int _StatusCode, int _CompanyID) {
            this.Invoke("DeactivateManager", new object[] {
                        _Guid,
                        _ManagerID,
                        _UserGuid,
                        _AlternateManagerID,
                        _StatusCode,
                        _CompanyID});
        }
        
        /// <remarks/>
        public void DeactivateManagerAsync(System.Guid _Guid, System.Guid _ManagerID, System.Guid _UserGuid, System.Guid _AlternateManagerID, int _StatusCode, int _CompanyID) {
            this.DeactivateManagerAsync(_Guid, _ManagerID, _UserGuid, _AlternateManagerID, _StatusCode, _CompanyID, null);
        }
        
        /// <remarks/>
        public void DeactivateManagerAsync(System.Guid _Guid, System.Guid _ManagerID, System.Guid _UserGuid, System.Guid _AlternateManagerID, int _StatusCode, int _CompanyID, object userState) {
            if ((this.DeactivateManagerOperationCompleted == null)) {
                this.DeactivateManagerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeactivateManagerOperationCompleted);
            }
            this.InvokeAsync("DeactivateManager", new object[] {
                        _Guid,
                        _ManagerID,
                        _UserGuid,
                        _AlternateManagerID,
                        _StatusCode,
                        _CompanyID}, this.DeactivateManagerOperationCompleted, userState);
        }
        
        private void OnDeactivateManagerOperationCompleted(object arg) {
            if ((this.DeactivateManagerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeactivateManagerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTeam", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKN_P_GetTeam_Result[] GetTeam(string _ManagerID, int _CompanyID) {
            object[] results = this.Invoke("GetTeam", new object[] {
                        _ManagerID,
                        _CompanyID});
            return ((YKN_P_GetTeam_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTeamAsync(string _ManagerID, int _CompanyID) {
            this.GetTeamAsync(_ManagerID, _CompanyID, null);
        }
        
        /// <remarks/>
        public void GetTeamAsync(string _ManagerID, int _CompanyID, object userState) {
            if ((this.GetTeamOperationCompleted == null)) {
                this.GetTeamOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeamOperationCompleted);
            }
            this.InvokeAsync("GetTeam", new object[] {
                        _ManagerID,
                        _CompanyID}, this.GetTeamOperationCompleted, userState);
        }
        
        private void OnGetTeamOperationCompleted(object arg) {
            if ((this.GetTeamCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeamCompleted(this, new GetTeamCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTeamManagers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKN_P_GetTeamManagers_Result[] GetTeamManagers(int _CompanyID) {
            object[] results = this.Invoke("GetTeamManagers", new object[] {
                        _CompanyID});
            return ((YKN_P_GetTeamManagers_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTeamManagersAsync(int _CompanyID) {
            this.GetTeamManagersAsync(_CompanyID, null);
        }
        
        /// <remarks/>
        public void GetTeamManagersAsync(int _CompanyID, object userState) {
            if ((this.GetTeamManagersOperationCompleted == null)) {
                this.GetTeamManagersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTeamManagersOperationCompleted);
            }
            this.InvokeAsync("GetTeamManagers", new object[] {
                        _CompanyID}, this.GetTeamManagersOperationCompleted, userState);
        }
        
        private void OnGetTeamManagersOperationCompleted(object arg) {
            if ((this.GetTeamManagersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTeamManagersCompleted(this, new GetTeamManagersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKN_P_GetSalesRepList_Result {
        
        private string salesRepNameField;
        
        private System.Guid salesRepGUIDField;
        
        /// <remarks/>
        public string salesRepName {
            get {
                return this.salesRepNameField;
            }
            set {
                this.salesRepNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid salesRepGUID {
            get {
                return this.salesRepGUIDField;
            }
            set {
                this.salesRepGUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKN_P_GetTeamManagers_Result {
        
        private System.Nullable<long> rowNumField;
        
        private string managerNameField;
        
        private string managerIDField;
        
        private System.Guid managerGuidField;
        
        private string new_MobileField;
        
        private System.Nullable<System.DateTime> activeDateField;
        
        private System.Nullable<int> statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> RowNum {
            get {
                return this.rowNumField;
            }
            set {
                this.rowNumField = value;
            }
        }
        
        /// <remarks/>
        public string ManagerName {
            get {
                return this.managerNameField;
            }
            set {
                this.managerNameField = value;
            }
        }
        
        /// <remarks/>
        public string ManagerID {
            get {
                return this.managerIDField;
            }
            set {
                this.managerIDField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ManagerGuid {
            get {
                return this.managerGuidField;
            }
            set {
                this.managerGuidField = value;
            }
        }
        
        /// <remarks/>
        public string new_Mobile {
            get {
                return this.new_MobileField;
            }
            set {
                this.new_MobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ActiveDate {
            get {
                return this.activeDateField;
            }
            set {
                this.activeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKN_P_GetTeam_Result {
        
        private System.Nullable<long> rowNumField;
        
        private string salesRepNameField;
        
        private System.Guid salesRepIDField;
        
        private System.Nullable<System.Guid> managerGuidField;
        
        private string managerNameField;
        
        private string new_MobileField;
        
        private System.Nullable<System.DateTime> activeDateField;
        
        private System.Nullable<int> statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> RowNum {
            get {
                return this.rowNumField;
            }
            set {
                this.rowNumField = value;
            }
        }
        
        /// <remarks/>
        public string SalesRepName {
            get {
                return this.salesRepNameField;
            }
            set {
                this.salesRepNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid SalesRepID {
            get {
                return this.salesRepIDField;
            }
            set {
                this.salesRepIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> ManagerGuid {
            get {
                return this.managerGuidField;
            }
            set {
                this.managerGuidField = value;
            }
        }
        
        /// <remarks/>
        public string ManagerName {
            get {
                return this.managerNameField;
            }
            set {
                this.managerNameField = value;
            }
        }
        
        /// <remarks/>
        public string new_Mobile {
            get {
                return this.new_MobileField;
            }
            set {
                this.new_MobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ActiveDate {
            get {
                return this.activeDateField;
            }
            set {
                this.activeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKN_P_GetManagerList_Result {
        
        private string managerNameField;
        
        private System.Guid managerGUIDField;
        
        /// <remarks/>
        public string ManagerName {
            get {
                return this.managerNameField;
            }
            set {
                this.managerNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ManagerGUID {
            get {
                return this.managerGUIDField;
            }
            set {
                this.managerGUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetSalesRepListCompletedEventHandler(object sender, GetSalesRepListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSalesRepListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSalesRepListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKN_P_GetSalesRepList_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKN_P_GetSalesRepList_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetManagerListCompletedEventHandler(object sender, GetManagerListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetManagerListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetManagerListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKN_P_GetManagerList_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKN_P_GetManagerList_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ActivateDeactivateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void DeactivateManagerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTeamCompletedEventHandler(object sender, GetTeamCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeamCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeamCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKN_P_GetTeam_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKN_P_GetTeam_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetTeamManagersCompletedEventHandler(object sender, GetTeamManagersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTeamManagersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTeamManagersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKN_P_GetTeamManagers_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKN_P_GetTeamManagers_Result[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591