//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IDH.Sales.BLL.StockWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StockWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class StockWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockItemByCategoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockReportDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AssignStockItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StockWebService() {
            this.Url = global::IDH.Sales.BLL.Properties.Settings.Default.IDH_Sales_BLL_StockWebReference_StockWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetStockCompletedEventHandler GetStockCompleted;
        
        /// <remarks/>
        public event GetStockCategoryCompletedEventHandler GetStockCategoryCompleted;
        
        /// <remarks/>
        public event GetStockItemByCategoryCompletedEventHandler GetStockItemByCategoryCompleted;
        
        /// <remarks/>
        public event GetStockReportDetailsCompletedEventHandler GetStockReportDetailsCompleted;
        
        /// <remarks/>
        public event AssignStockItemCompletedEventHandler AssignStockItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKN_P_GetStock_Result[] GetStock(string _SalesRepID, string _CategoryID, int _CompanyID, int _Month, string _UserID, string _ItemID) {
            object[] results = this.Invoke("GetStock", new object[] {
                        _SalesRepID,
                        _CategoryID,
                        _CompanyID,
                        _Month,
                        _UserID,
                        _ItemID});
            return ((YKN_P_GetStock_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStockAsync(string _SalesRepID, string _CategoryID, int _CompanyID, int _Month, string _UserID, string _ItemID) {
            this.GetStockAsync(_SalesRepID, _CategoryID, _CompanyID, _Month, _UserID, _ItemID, null);
        }
        
        /// <remarks/>
        public void GetStockAsync(string _SalesRepID, string _CategoryID, int _CompanyID, int _Month, string _UserID, string _ItemID, object userState) {
            if ((this.GetStockOperationCompleted == null)) {
                this.GetStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockOperationCompleted);
            }
            this.InvokeAsync("GetStock", new object[] {
                        _SalesRepID,
                        _CategoryID,
                        _CompanyID,
                        _Month,
                        _UserID,
                        _ItemID}, this.GetStockOperationCompleted, userState);
        }
        
        private void OnGetStockOperationCompleted(object arg) {
            if ((this.GetStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockCompleted(this, new GetStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKN_P_GetStockCategory_Result[] GetStockCategory(string _UserID, int _CompanyID) {
            object[] results = this.Invoke("GetStockCategory", new object[] {
                        _UserID,
                        _CompanyID});
            return ((YKN_P_GetStockCategory_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStockCategoryAsync(string _UserID, int _CompanyID) {
            this.GetStockCategoryAsync(_UserID, _CompanyID, null);
        }
        
        /// <remarks/>
        public void GetStockCategoryAsync(string _UserID, int _CompanyID, object userState) {
            if ((this.GetStockCategoryOperationCompleted == null)) {
                this.GetStockCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockCategoryOperationCompleted);
            }
            this.InvokeAsync("GetStockCategory", new object[] {
                        _UserID,
                        _CompanyID}, this.GetStockCategoryOperationCompleted, userState);
        }
        
        private void OnGetStockCategoryOperationCompleted(object arg) {
            if ((this.GetStockCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockCategoryCompleted(this, new GetStockCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockItemByCategory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKN_P_GetStockitemByCategory_Result[] GetStockItemByCategory(System.Guid _CategoryID, string _SalesRepID, int _CompanyID) {
            object[] results = this.Invoke("GetStockItemByCategory", new object[] {
                        _CategoryID,
                        _SalesRepID,
                        _CompanyID});
            return ((YKN_P_GetStockitemByCategory_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStockItemByCategoryAsync(System.Guid _CategoryID, string _SalesRepID, int _CompanyID) {
            this.GetStockItemByCategoryAsync(_CategoryID, _SalesRepID, _CompanyID, null);
        }
        
        /// <remarks/>
        public void GetStockItemByCategoryAsync(System.Guid _CategoryID, string _SalesRepID, int _CompanyID, object userState) {
            if ((this.GetStockItemByCategoryOperationCompleted == null)) {
                this.GetStockItemByCategoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockItemByCategoryOperationCompleted);
            }
            this.InvokeAsync("GetStockItemByCategory", new object[] {
                        _CategoryID,
                        _SalesRepID,
                        _CompanyID}, this.GetStockItemByCategoryOperationCompleted, userState);
        }
        
        private void OnGetStockItemByCategoryOperationCompleted(object arg) {
            if ((this.GetStockItemByCategoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockItemByCategoryCompleted(this, new GetStockItemByCategoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockReportDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKN_P_GetStockReportDetails_Result[] GetStockReportDetails(int _CompanyID, int _Month, string _UserID, string _RoleID) {
            object[] results = this.Invoke("GetStockReportDetails", new object[] {
                        _CompanyID,
                        _Month,
                        _UserID,
                        _RoleID});
            return ((YKN_P_GetStockReportDetails_Result[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStockReportDetailsAsync(int _CompanyID, int _Month, string _UserID, string _RoleID) {
            this.GetStockReportDetailsAsync(_CompanyID, _Month, _UserID, _RoleID, null);
        }
        
        /// <remarks/>
        public void GetStockReportDetailsAsync(int _CompanyID, int _Month, string _UserID, string _RoleID, object userState) {
            if ((this.GetStockReportDetailsOperationCompleted == null)) {
                this.GetStockReportDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockReportDetailsOperationCompleted);
            }
            this.InvokeAsync("GetStockReportDetails", new object[] {
                        _CompanyID,
                        _Month,
                        _UserID,
                        _RoleID}, this.GetStockReportDetailsOperationCompleted, userState);
        }
        
        private void OnGetStockReportDetailsOperationCompleted(object arg) {
            if ((this.GetStockReportDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockReportDetailsCompleted(this, new GetStockReportDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AssignStockItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AssignStockItem(System.Guid _UserID, System.Guid _ItemID, System.Guid _SalesRepID, int _Qty, int _CompanyID, System.Guid _Guid) {
            this.Invoke("AssignStockItem", new object[] {
                        _UserID,
                        _ItemID,
                        _SalesRepID,
                        _Qty,
                        _CompanyID,
                        _Guid});
        }
        
        /// <remarks/>
        public void AssignStockItemAsync(System.Guid _UserID, System.Guid _ItemID, System.Guid _SalesRepID, int _Qty, int _CompanyID, System.Guid _Guid) {
            this.AssignStockItemAsync(_UserID, _ItemID, _SalesRepID, _Qty, _CompanyID, _Guid, null);
        }
        
        /// <remarks/>
        public void AssignStockItemAsync(System.Guid _UserID, System.Guid _ItemID, System.Guid _SalesRepID, int _Qty, int _CompanyID, System.Guid _Guid, object userState) {
            if ((this.AssignStockItemOperationCompleted == null)) {
                this.AssignStockItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssignStockItemOperationCompleted);
            }
            this.InvokeAsync("AssignStockItem", new object[] {
                        _UserID,
                        _ItemID,
                        _SalesRepID,
                        _Qty,
                        _CompanyID,
                        _Guid}, this.AssignStockItemOperationCompleted, userState);
        }
        
        private void OnAssignStockItemOperationCompleted(object arg) {
            if ((this.AssignStockItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AssignStockItemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKN_P_GetStock_Result {
        
        private string itemNameField;
        
        private System.Nullable<int> startBalanceField;
        
        private System.Nullable<int> new_BalanceField;
        
        private System.Nullable<System.Guid> categoryIDField;
        
        /// <remarks/>
        public string itemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> StartBalance {
            get {
                return this.startBalanceField;
            }
            set {
                this.startBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> new_Balance {
            get {
                return this.new_BalanceField;
            }
            set {
                this.new_BalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> categoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKN_P_GetStockReportDetails_Result {
        
        private string itemNameField;
        
        private System.Guid itemGUIDField;
        
        private System.Nullable<int> totalStockField;
        
        private System.Nullable<int> availableStockField;
        
        private string salesRepNameField;
        
        private string directManagerNameField;
        
        private System.Nullable<int> visitNoField;
        
        private string categoryNameField;
        
        /// <remarks/>
        public string itemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid itemGUID {
            get {
                return this.itemGUIDField;
            }
            set {
                this.itemGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TotalStock {
            get {
                return this.totalStockField;
            }
            set {
                this.totalStockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> availableStock {
            get {
                return this.availableStockField;
            }
            set {
                this.availableStockField = value;
            }
        }
        
        /// <remarks/>
        public string salesRepName {
            get {
                return this.salesRepNameField;
            }
            set {
                this.salesRepNameField = value;
            }
        }
        
        /// <remarks/>
        public string DirectManagerName {
            get {
                return this.directManagerNameField;
            }
            set {
                this.directManagerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> VisitNo {
            get {
                return this.visitNoField;
            }
            set {
                this.visitNoField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKN_P_GetStockitemByCategory_Result {
        
        private string stockitemNameField;
        
        private System.Nullable<System.Guid> stockItemGUIDField;
        
        private System.Nullable<int> balanceField;
        
        /// <remarks/>
        public string StockitemName {
            get {
                return this.stockitemNameField;
            }
            set {
                this.stockitemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> StockItemGUID {
            get {
                return this.stockItemGUIDField;
            }
            set {
                this.stockItemGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKN_P_GetStockCategory_Result {
        
        private string categoryNameField;
        
        private System.Guid categoryIDField;
        
        /// <remarks/>
        public string categoryName {
            get {
                return this.categoryNameField;
            }
            set {
                this.categoryNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStockCompletedEventHandler(object sender, GetStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKN_P_GetStock_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKN_P_GetStock_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStockCategoryCompletedEventHandler(object sender, GetStockCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKN_P_GetStockCategory_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKN_P_GetStockCategory_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStockItemByCategoryCompletedEventHandler(object sender, GetStockItemByCategoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockItemByCategoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockItemByCategoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKN_P_GetStockitemByCategory_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKN_P_GetStockitemByCategory_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStockReportDetailsCompletedEventHandler(object sender, GetStockReportDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockReportDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockReportDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKN_P_GetStockReportDetails_Result[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKN_P_GetStockReportDetails_Result[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AssignStockItemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591