//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDH.Sales.BLL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://yakensolution.cloudapp.net/IDHServices/Services/VisitWebService.asmx")]
        public string IDH_Sales_BLL_VisitServiceReference_VisitWebService {
            get {
                return ((string)(this["IDH_Sales_BLL_VisitServiceReference_VisitWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://yakensolution.cloudapp.net/IDHServices/Services/SalesRepWebService.asmx")]
        public string IDH_Sales_BLL_SalesRepWebReference_SalesRepWebService {
            get {
                return ((string)(this["IDH_Sales_BLL_SalesRepWebReference_SalesRepWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://yakensolution.cloudapp.net/IDHServices/Services/StockWebService.asmx")]
        public string IDH_Sales_BLL_StockWebReference_StockWebService {
            get {
                return ((string)(this["IDH_Sales_BLL_StockWebReference_StockWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://yakensolution.cloudapp.net/IDHServices/Services/UserWebService.asmx")]
        public string IDH_Sales_BLL_UserServiceReference_UserWebService {
            get {
                return ((string)(this["IDH_Sales_BLL_UserServiceReference_UserWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://yakensolution.cloudapp.net/IDHServices/Services/DoctorWebService.asmx")]
        public string IDH_Sales_BLL_DoctorWebReference_DoctorWebService {
            get {
                return ((string)(this["IDH_Sales_BLL_DoctorWebReference_DoctorWebService"]));
            }
        }
    }
}
