//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDH.Sales.DAL.CRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<YKN_P_GetAVTDetails_Result> YKN_P_GetAVTDetails(Nullable<int> companyId, Nullable<int> month, string userID, string roleID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var roleIDParameter = roleID != null ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetAVTDetails_Result>("YKN_P_GetAVTDetails", companyIdParameter, monthParameter, userIDParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetCustomerReport_Result> YKN_P_GetCustomerReport(Nullable<System.DateTime> endDate, Nullable<System.DateTime> startDate, string userID, string ruleID)
        {
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var ruleIDParameter = ruleID != null ?
                new ObjectParameter("RuleID", ruleID) :
                new ObjectParameter("RuleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetCustomerReport_Result>("YKN_P_GetCustomerReport", endDateParameter, startDateParameter, userIDParameter, ruleIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetDashInfo_Result> YKN_P_GetDashInfo(Nullable<int> companyId, Nullable<int> month, string userID, string roleID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var roleIDParameter = roleID != null ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetDashInfo_Result>("YKN_P_GetDashInfo", companyIdParameter, monthParameter, userIDParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetManagerList_Result> YKN_P_GetManagerList(Nullable<int> companyID)
        {
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("CompanyID", companyID) :
                new ObjectParameter("CompanyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetManagerList_Result>("YKN_P_GetManagerList", companyIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetMapLocation_Result> YKN_P_GetMapLocation(Nullable<System.DateTime> day, string salesRepGUID)
        {
            var dayParameter = day.HasValue ?
                new ObjectParameter("Day", day) :
                new ObjectParameter("Day", typeof(System.DateTime));
    
            var salesRepGUIDParameter = salesRepGUID != null ?
                new ObjectParameter("SalesRepGUID", salesRepGUID) :
                new ObjectParameter("SalesRepGUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetMapLocation_Result>("YKN_P_GetMapLocation", dayParameter, salesRepGUIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetMissedVisitList_Result> YKN_P_GetMissedVisitList(Nullable<int> companyId, Nullable<int> month, string userID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetMissedVisitList_Result>("YKN_P_GetMissedVisitList", companyIdParameter, monthParameter, userIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetMonthPlan_Result> YKN_P_GetMonthPlan(Nullable<int> companyId, Nullable<int> month, string userID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetMonthPlan_Result>("YKN_P_GetMonthPlan", companyIdParameter, monthParameter, userIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetOrgList_Result> YKN_P_GetOrgList(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetOrgList_Result>("YKN_P_GetOrgList", companyIdParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetProfessionalList_Result> YKN_P_GetProfessionalList(string roleID, Nullable<int> companyId, string userID, Nullable<int> ownlist)
        {
            var roleIDParameter = roleID != null ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var ownlistParameter = ownlist.HasValue ?
                new ObjectParameter("ownlist", ownlist) :
                new ObjectParameter("ownlist", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetProfessionalList_Result>("YKN_P_GetProfessionalList", roleIDParameter, companyIdParameter, userIDParameter, ownlistParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetProfissionalOrgList_Result> YKN_P_GetProfissionalOrgList(Nullable<int> companyId, Nullable<System.Guid> profisonalGUID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var profisonalGUIDParameter = profisonalGUID.HasValue ?
                new ObjectParameter("ProfisonalGUID", profisonalGUID) :
                new ObjectParameter("ProfisonalGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetProfissionalOrgList_Result>("YKN_P_GetProfissionalOrgList", companyIdParameter, profisonalGUIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetSalesRepList_Result> YKN_P_GetSalesRepList(string roleGUID, string userGUID)
        {
            var roleGUIDParameter = roleGUID != null ?
                new ObjectParameter("RoleGUID", roleGUID) :
                new ObjectParameter("RoleGUID", typeof(string));
    
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetSalesRepList_Result>("YKN_P_GetSalesRepList", roleGUIDParameter, userGUIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetSpecialityList_Result> YKN_P_GetSpecialityList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetSpecialityList_Result>("YKN_P_GetSpecialityList");
        }
    
        public virtual ObjectResult<YKN_P_GetStock_Result> YKN_P_GetStock(string salesRepID, string categoryID, Nullable<int> companyId, Nullable<int> month, string userID, string itemID)
        {
            var salesRepIDParameter = salesRepID != null ?
                new ObjectParameter("salesRepID", salesRepID) :
                new ObjectParameter("salesRepID", typeof(string));
    
            var categoryIDParameter = categoryID != null ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var itemIDParameter = itemID != null ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetStock_Result>("YKN_P_GetStock", salesRepIDParameter, categoryIDParameter, companyIdParameter, monthParameter, userIDParameter, itemIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetStockCategory_Result> YKN_P_GetStockCategory(string userID, Nullable<int> companyId)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetStockCategory_Result>("YKN_P_GetStockCategory", userIDParameter, companyIdParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetStockitemByCategory_Result> YKN_P_GetStockitemByCategory(Nullable<System.Guid> categoryID, string salesRepID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(System.Guid));
    
            var salesRepIDParameter = salesRepID != null ?
                new ObjectParameter("salesRepID", salesRepID) :
                new ObjectParameter("salesRepID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetStockitemByCategory_Result>("YKN_P_GetStockitemByCategory", categoryIDParameter, salesRepIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetStockReportDetails_Result> YKN_P_GetStockReportDetails(Nullable<int> companyId, Nullable<int> month, string userID, string roleID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var roleIDParameter = roleID != null ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetStockReportDetails_Result>("YKN_P_GetStockReportDetails", companyIdParameter, monthParameter, userIDParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetTargetAchievedDetails_Result> YKN_P_GetTargetAchievedDetails(Nullable<int> companyId, Nullable<int> month, string userID, string roleID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var roleIDParameter = roleID != null ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetTargetAchievedDetails_Result>("YKN_P_GetTargetAchievedDetails", companyIdParameter, monthParameter, userIDParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetTeam_Result> YKN_P_GetTeam(string managerGUID, Nullable<int> companyId)
        {
            var managerGUIDParameter = managerGUID != null ?
                new ObjectParameter("ManagerGUID", managerGUID) :
                new ObjectParameter("ManagerGUID", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetTeam_Result>("YKN_P_GetTeam", managerGUIDParameter, companyIdParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetTeamManagers_Result> YKN_P_GetTeamManagers(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetTeamManagers_Result>("YKN_P_GetTeamManagers", companyIdParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetTestList_Result> YKN_P_GetTestList(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetTestList_Result>("YKN_P_GetTestList", companyIdParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetUnAssignedProfessionals_Result> YKN_P_GetUnAssignedProfessionals(Nullable<int> companyId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetUnAssignedProfessionals_Result>("YKN_P_GetUnAssignedProfessionals", companyIdParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetUserData_Result> YKN_P_GetUserData(string userName, string pasword, Nullable<int> companyId)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var paswordParameter = pasword != null ?
                new ObjectParameter("Pasword", pasword) :
                new ObjectParameter("Pasword", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetUserData_Result>("YKN_P_GetUserData", userNameParameter, paswordParameter, companyIdParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetUserDataGUID_Result> YKN_P_GetUserDataGUID(string userGUID)
        {
            var userGUIDParameter = userGUID != null ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetUserDataGUID_Result>("YKN_P_GetUserDataGUID", userGUIDParameter);
        }
    
        public virtual ObjectResult<YKN_PH_GetCancelReasons_Result> YKN_PH_GetCancelReasons()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_PH_GetCancelReasons_Result>("YKN_PH_GetCancelReasons");
        }
    
        public virtual ObjectResult<YKN_PH_GetFeedbacklist_Result> YKN_PH_GetFeedbacklist()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_PH_GetFeedbacklist_Result>("YKN_PH_GetFeedbacklist");
        }
    
        public virtual ObjectResult<YKN_PH_GetMaxMinPlan_Result> YKN_PH_GetMaxMinPlan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_PH_GetMaxMinPlan_Result>("YKN_PH_GetMaxMinPlan");
        }
    
        public virtual ObjectResult<YKN_PH_GetProfessionalTier_Result> YKN_PH_GetProfessionalTier()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_PH_GetProfessionalTier_Result>("YKN_PH_GetProfessionalTier");
        }
    
        public virtual ObjectResult<YKN_PH_GetVisitStatusList_Result> YKN_PH_GetVisitStatusList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_PH_GetVisitStatusList_Result>("YKN_PH_GetVisitStatusList");
        }
    
        public virtual int YKN_Push_ActivateDeactivateSalesRep(Nullable<System.Guid> gUID, Nullable<System.Guid> managerGUID, Nullable<System.Guid> userGUID, Nullable<System.Guid> salesRepGUID, Nullable<int> statusCode, Nullable<int> companyId)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var managerGUIDParameter = managerGUID.HasValue ?
                new ObjectParameter("ManagerGUID", managerGUID) :
                new ObjectParameter("ManagerGUID", typeof(System.Guid));
    
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            var salesRepGUIDParameter = salesRepGUID.HasValue ?
                new ObjectParameter("SalesRepGUID", salesRepGUID) :
                new ObjectParameter("SalesRepGUID", typeof(System.Guid));
    
            var statusCodeParameter = statusCode.HasValue ?
                new ObjectParameter("StatusCode", statusCode) :
                new ObjectParameter("StatusCode", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_ActivateDeactivateSalesRep", gUIDParameter, managerGUIDParameter, userGUIDParameter, salesRepGUIDParameter, statusCodeParameter, companyIdParameter);
        }
    
        public virtual int YKN_Push_AddOrganization(Nullable<System.Guid> gUID, Nullable<System.Guid> userGUID, Nullable<int> status, string orgName, string orgSdress, string phoneNumber)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var orgNameParameter = orgName != null ?
                new ObjectParameter("OrgName", orgName) :
                new ObjectParameter("OrgName", typeof(string));
    
            var orgSdressParameter = orgSdress != null ?
                new ObjectParameter("OrgSdress", orgSdress) :
                new ObjectParameter("OrgSdress", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_AddOrganization", gUIDParameter, userGUIDParameter, statusParameter, orgNameParameter, orgSdressParameter, phoneNumberParameter);
        }
    
        public virtual int YKN_Push_AddProfessional(Nullable<System.Guid> gUID, Nullable<System.Guid> userGUID, Nullable<int> status, string professionalName, Nullable<int> professionalTier, string mobileNo, Nullable<System.Guid> specialityID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var professionalNameParameter = professionalName != null ?
                new ObjectParameter("professionalName", professionalName) :
                new ObjectParameter("professionalName", typeof(string));
    
            var professionalTierParameter = professionalTier.HasValue ?
                new ObjectParameter("ProfessionalTier", professionalTier) :
                new ObjectParameter("ProfessionalTier", typeof(int));
    
            var mobileNoParameter = mobileNo != null ?
                new ObjectParameter("mobileNo", mobileNo) :
                new ObjectParameter("mobileNo", typeof(string));
    
            var specialityIDParameter = specialityID.HasValue ?
                new ObjectParameter("specialityID", specialityID) :
                new ObjectParameter("specialityID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_AddProfessional", gUIDParameter, userGUIDParameter, statusParameter, professionalNameParameter, professionalTierParameter, mobileNoParameter, specialityIDParameter);
        }
    
        public virtual int YKN_Push_AddProfessionalOrg(Nullable<System.Guid> gUID, Nullable<System.Guid> professionalGUID, Nullable<System.Guid> orgGUID, Nullable<int> type)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var professionalGUIDParameter = professionalGUID.HasValue ?
                new ObjectParameter("ProfessionalGUID", professionalGUID) :
                new ObjectParameter("ProfessionalGUID", typeof(System.Guid));
    
            var orgGUIDParameter = orgGUID.HasValue ?
                new ObjectParameter("OrgGUID", orgGUID) :
                new ObjectParameter("OrgGUID", typeof(System.Guid));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_AddProfessionalOrg", gUIDParameter, professionalGUIDParameter, orgGUIDParameter, typeParameter);
        }
    
        public virtual int YKN_Push_AddtestFeedBack(Nullable<System.Guid> gUID, Nullable<System.Guid> visitGUID, Nullable<System.Guid> testGUID, Nullable<int> feedBackId, string comment, Nullable<int> companyId)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var visitGUIDParameter = visitGUID.HasValue ?
                new ObjectParameter("VisitGUID", visitGUID) :
                new ObjectParameter("VisitGUID", typeof(System.Guid));
    
            var testGUIDParameter = testGUID.HasValue ?
                new ObjectParameter("TestGUID", testGUID) :
                new ObjectParameter("TestGUID", typeof(System.Guid));
    
            var feedBackIdParameter = feedBackId.HasValue ?
                new ObjectParameter("feedBackId", feedBackId) :
                new ObjectParameter("feedBackId", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_AddtestFeedBack", gUIDParameter, visitGUIDParameter, testGUIDParameter, feedBackIdParameter, commentParameter, companyIdParameter);
        }
    
        public virtual int YKN_Push_AddVisitHeader(Nullable<System.Guid> gUID, Nullable<int> visitCode, Nullable<System.Guid> professionalGuid, Nullable<System.Guid> orgGuid, Nullable<System.Guid> salesRepGuid, Nullable<System.DateTime> visitDate, Nullable<int> visitLevel, Nullable<int> companyId, Nullable<System.Guid> userGUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var visitCodeParameter = visitCode.HasValue ?
                new ObjectParameter("VisitCode", visitCode) :
                new ObjectParameter("VisitCode", typeof(int));
    
            var professionalGuidParameter = professionalGuid.HasValue ?
                new ObjectParameter("professionalGuid", professionalGuid) :
                new ObjectParameter("professionalGuid", typeof(System.Guid));
    
            var orgGuidParameter = orgGuid.HasValue ?
                new ObjectParameter("OrgGuid", orgGuid) :
                new ObjectParameter("OrgGuid", typeof(System.Guid));
    
            var salesRepGuidParameter = salesRepGuid.HasValue ?
                new ObjectParameter("SalesRepGuid", salesRepGuid) :
                new ObjectParameter("SalesRepGuid", typeof(System.Guid));
    
            var visitDateParameter = visitDate.HasValue ?
                new ObjectParameter("VisitDate", visitDate) :
                new ObjectParameter("VisitDate", typeof(System.DateTime));
    
            var visitLevelParameter = visitLevel.HasValue ?
                new ObjectParameter("VisitLevel", visitLevel) :
                new ObjectParameter("VisitLevel", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_AddVisitHeader", gUIDParameter, visitCodeParameter, professionalGuidParameter, orgGuidParameter, salesRepGuidParameter, visitDateParameter, visitLevelParameter, companyIdParameter, userGUIDParameter);
        }
    
        public virtual int YKN_Push_AddvisitStock(Nullable<System.Guid> gUID, Nullable<System.Guid> visitGUID, Nullable<System.Guid> stockItemGUID, Nullable<int> qnty, Nullable<System.Guid> userGUID, Nullable<int> companyId)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var visitGUIDParameter = visitGUID.HasValue ?
                new ObjectParameter("VisitGUID", visitGUID) :
                new ObjectParameter("VisitGUID", typeof(System.Guid));
    
            var stockItemGUIDParameter = stockItemGUID.HasValue ?
                new ObjectParameter("StockItemGUID", stockItemGUID) :
                new ObjectParameter("StockItemGUID", typeof(System.Guid));
    
            var qntyParameter = qnty.HasValue ?
                new ObjectParameter("Qnty", qnty) :
                new ObjectParameter("Qnty", typeof(int));
    
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("companyId", companyId) :
                new ObjectParameter("companyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_AddvisitStock", gUIDParameter, visitGUIDParameter, stockItemGUIDParameter, qntyParameter, userGUIDParameter, companyIdParameter);
        }
    
        public virtual int YKN_Push_AssignProfessional(Nullable<System.Guid> gUID, Nullable<System.Guid> professionalGUID, Nullable<System.Guid> salesRepGUID, Nullable<int> companyId)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var professionalGUIDParameter = professionalGUID.HasValue ?
                new ObjectParameter("ProfessionalGUID", professionalGUID) :
                new ObjectParameter("ProfessionalGUID", typeof(System.Guid));
    
            var salesRepGUIDParameter = salesRepGUID.HasValue ?
                new ObjectParameter("SalesRepGUID", salesRepGUID) :
                new ObjectParameter("SalesRepGUID", typeof(System.Guid));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("companyId", companyId) :
                new ObjectParameter("companyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_AssignProfessional", gUIDParameter, professionalGUIDParameter, salesRepGUIDParameter, companyIdParameter);
        }
    
        public virtual int YKN_Push_AssignStockItem(Nullable<System.Guid> userGUID, Nullable<System.Guid> itemGUID, Nullable<System.Guid> salesRepGUID, Nullable<int> qty, Nullable<int> companyId, Nullable<System.Guid> guid)
        {
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            var itemGUIDParameter = itemGUID.HasValue ?
                new ObjectParameter("ItemGUID", itemGUID) :
                new ObjectParameter("ItemGUID", typeof(System.Guid));
    
            var salesRepGUIDParameter = salesRepGUID.HasValue ?
                new ObjectParameter("SalesRepGUID", salesRepGUID) :
                new ObjectParameter("SalesRepGUID", typeof(System.Guid));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("companyId", companyId) :
                new ObjectParameter("companyId", typeof(int));
    
            var guidParameter = guid.HasValue ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_AssignStockItem", userGUIDParameter, itemGUIDParameter, salesRepGUIDParameter, qtyParameter, companyIdParameter, guidParameter);
        }
    
        public virtual int YKN_Push_ChangeVisitStatus(Nullable<System.Guid> visitGUID, Nullable<int> visitstatus, Nullable<int> companyID)
        {
            var visitGUIDParameter = visitGUID.HasValue ?
                new ObjectParameter("VisitGUID", visitGUID) :
                new ObjectParameter("VisitGUID", typeof(System.Guid));
    
            var visitstatusParameter = visitstatus.HasValue ?
                new ObjectParameter("Visitstatus", visitstatus) :
                new ObjectParameter("Visitstatus", typeof(int));
    
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("companyID", companyID) :
                new ObjectParameter("companyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_ChangeVisitStatus", visitGUIDParameter, visitstatusParameter, companyIDParameter);
        }
    
        public virtual int YKN_Push_DeactivateManager(Nullable<System.Guid> gUID, Nullable<System.Guid> userGUID, Nullable<System.Guid> managerGUID, Nullable<System.Guid> ultrnateManagerGUID, Nullable<int> statusCode, Nullable<int> companyId)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            var managerGUIDParameter = managerGUID.HasValue ?
                new ObjectParameter("ManagerGUID", managerGUID) :
                new ObjectParameter("ManagerGUID", typeof(System.Guid));
    
            var ultrnateManagerGUIDParameter = ultrnateManagerGUID.HasValue ?
                new ObjectParameter("UltrnateManagerGUID", ultrnateManagerGUID) :
                new ObjectParameter("UltrnateManagerGUID", typeof(System.Guid));
    
            var statusCodeParameter = statusCode.HasValue ?
                new ObjectParameter("StatusCode", statusCode) :
                new ObjectParameter("StatusCode", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_DeactivateManager", gUIDParameter, userGUIDParameter, managerGUIDParameter, ultrnateManagerGUIDParameter, statusCodeParameter, companyIdParameter);
        }
    
        public virtual int YKN_Push_ReAssignProfessional(Nullable<System.Guid> gUID, Nullable<System.Guid> userGUID, Nullable<System.Guid> professionalGUID, Nullable<System.Guid> salesRepGUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("UserGUID", userGUID) :
                new ObjectParameter("UserGUID", typeof(System.Guid));
    
            var professionalGUIDParameter = professionalGUID.HasValue ?
                new ObjectParameter("ProfessionalGUID", professionalGUID) :
                new ObjectParameter("ProfessionalGUID", typeof(System.Guid));
    
            var salesRepGUIDParameter = salesRepGUID.HasValue ?
                new ObjectParameter("SalesRepGUID", salesRepGUID) :
                new ObjectParameter("SalesRepGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_ReAssignProfessional", gUIDParameter, userGUIDParameter, professionalGUIDParameter, salesRepGUIDParameter);
        }
    
        public virtual int YKN_Push_ReschoduleVisit(Nullable<System.Guid> visitGUID, Nullable<System.DateTime> visitDate, Nullable<int> companyID)
        {
            var visitGUIDParameter = visitGUID.HasValue ?
                new ObjectParameter("VisitGUID", visitGUID) :
                new ObjectParameter("VisitGUID", typeof(System.Guid));
    
            var visitDateParameter = visitDate.HasValue ?
                new ObjectParameter("VisitDate", visitDate) :
                new ObjectParameter("VisitDate", typeof(System.DateTime));
    
            var companyIDParameter = companyID.HasValue ?
                new ObjectParameter("companyID", companyID) :
                new ObjectParameter("companyID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_ReschoduleVisit", visitGUIDParameter, visitDateParameter, companyIDParameter);
        }
    
        public virtual int YKN_Push_UpdateSalesRepProfessional(Nullable<System.Guid> gUID, Nullable<System.Guid> professionalGUID, Nullable<System.Guid> salesRepGUID)
        {
            var gUIDParameter = gUID.HasValue ?
                new ObjectParameter("GUID", gUID) :
                new ObjectParameter("GUID", typeof(System.Guid));
    
            var professionalGUIDParameter = professionalGUID.HasValue ?
                new ObjectParameter("ProfessionalGUID", professionalGUID) :
                new ObjectParameter("ProfessionalGUID", typeof(System.Guid));
    
            var salesRepGUIDParameter = salesRepGUID.HasValue ?
                new ObjectParameter("SalesRepGUID", salesRepGUID) :
                new ObjectParameter("SalesRepGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_UpdateSalesRepProfessional", gUIDParameter, professionalGUIDParameter, salesRepGUIDParameter);
        }
    
        public virtual int YKN_Push_UpdateVisitDetails(Nullable<System.Guid> visitGUID, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<decimal> startLat, Nullable<decimal> endLat, Nullable<decimal> startlong, Nullable<decimal> endlong, Nullable<int> visitstatus, string comment, Nullable<int> feedBackId, Nullable<int> companyId, string startAdress, string endAdress, Nullable<System.Guid> userGUID)
        {
            var visitGUIDParameter = visitGUID.HasValue ?
                new ObjectParameter("VisitGUID", visitGUID) :
                new ObjectParameter("VisitGUID", typeof(System.Guid));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var startLatParameter = startLat.HasValue ?
                new ObjectParameter("StartLat", startLat) :
                new ObjectParameter("StartLat", typeof(decimal));
    
            var endLatParameter = endLat.HasValue ?
                new ObjectParameter("endLat", endLat) :
                new ObjectParameter("endLat", typeof(decimal));
    
            var startlongParameter = startlong.HasValue ?
                new ObjectParameter("startlong", startlong) :
                new ObjectParameter("startlong", typeof(decimal));
    
            var endlongParameter = endlong.HasValue ?
                new ObjectParameter("endlong", endlong) :
                new ObjectParameter("endlong", typeof(decimal));
    
            var visitstatusParameter = visitstatus.HasValue ?
                new ObjectParameter("Visitstatus", visitstatus) :
                new ObjectParameter("Visitstatus", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var feedBackIdParameter = feedBackId.HasValue ?
                new ObjectParameter("feedBackId", feedBackId) :
                new ObjectParameter("feedBackId", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var startAdressParameter = startAdress != null ?
                new ObjectParameter("startAdress", startAdress) :
                new ObjectParameter("startAdress", typeof(string));
    
            var endAdressParameter = endAdress != null ?
                new ObjectParameter("EndAdress", endAdress) :
                new ObjectParameter("EndAdress", typeof(string));
    
            var userGUIDParameter = userGUID.HasValue ?
                new ObjectParameter("userGUID", userGUID) :
                new ObjectParameter("userGUID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_UpdateVisitDetails", visitGUIDParameter, startDateParameter, endDateParameter, startLatParameter, endLatParameter, startlongParameter, endlongParameter, visitstatusParameter, commentParameter, feedBackIdParameter, companyIdParameter, startAdressParameter, endAdressParameter, userGUIDParameter);
        }
    
        public virtual int YKN_Push_UpdateVisitHeader(Nullable<System.Guid> visitGUID, Nullable<System.DateTime> visitDate, Nullable<int> visitLevel, Nullable<int> visitstatus)
        {
            var visitGUIDParameter = visitGUID.HasValue ?
                new ObjectParameter("VisitGUID", visitGUID) :
                new ObjectParameter("VisitGUID", typeof(System.Guid));
    
            var visitDateParameter = visitDate.HasValue ?
                new ObjectParameter("VisitDate", visitDate) :
                new ObjectParameter("VisitDate", typeof(System.DateTime));
    
            var visitLevelParameter = visitLevel.HasValue ?
                new ObjectParameter("VisitLevel", visitLevel) :
                new ObjectParameter("VisitLevel", typeof(int));
    
            var visitstatusParameter = visitstatus.HasValue ?
                new ObjectParameter("Visitstatus", visitstatus) :
                new ObjectParameter("Visitstatus", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_UpdateVisitHeader", visitGUIDParameter, visitDateParameter, visitLevelParameter, visitstatusParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetDetailedRevReport_Result> YKN_P_GetDetailedRevReport(string salesRepGUID, Nullable<int> month, Nullable<int> year, Nullable<int> companyId, string roleID)
        {
            var salesRepGUIDParameter = salesRepGUID != null ?
                new ObjectParameter("SalesRepGUID", salesRepGUID) :
                new ObjectParameter("SalesRepGUID", typeof(string));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var roleIDParameter = roleID != null ?
                new ObjectParameter("RoleID", roleID) :
                new ObjectParameter("RoleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetDetailedRevReport_Result>("YKN_P_GetDetailedRevReport", salesRepGUIDParameter, monthParameter, yearParameter, companyIdParameter, roleIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetVisitByMonth_Result> YKN_P_GetVisitByMonth(Nullable<int> companyId, Nullable<int> month, Nullable<int> year, string userID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetVisitByMonth_Result>("YKN_P_GetVisitByMonth", companyIdParameter, monthParameter, yearParameter, userIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetVisitStock_Result> YKN_P_GetVisitStock(Nullable<int> companyId, Nullable<System.Guid> visitGUID, Nullable<System.Guid> userID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var visitGUIDParameter = visitGUID.HasValue ?
                new ObjectParameter("VisitGUID", visitGUID) :
                new ObjectParameter("VisitGUID", typeof(System.Guid));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetVisitStock_Result>("YKN_P_GetVisitStock", companyIdParameter, visitGUIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetVisitTests_Result> YKN_P_GetVisitTests(Nullable<int> companyId, Nullable<System.Guid> visitGUID, Nullable<System.Guid> userID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var visitGUIDParameter = visitGUID.HasValue ?
                new ObjectParameter("VisitGUID", visitGUID) :
                new ObjectParameter("VisitGUID", typeof(System.Guid));
    
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetVisitTests_Result>("YKN_P_GetVisitTests", companyIdParameter, visitGUIDParameter, userIDParameter);
        }
    
        public virtual ObjectResult<YKN_P_GetVisitByDay_Result> YKN_P_GetVisitByDay(Nullable<int> companyId, Nullable<System.DateTime> day, string userID)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var dayParameter = day.HasValue ?
                new ObjectParameter("Day", day) :
                new ObjectParameter("Day", typeof(System.DateTime));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YKN_P_GetVisitByDay_Result>("YKN_P_GetVisitByDay", companyIdParameter, dayParameter, userIDParameter);
        }
    
        public virtual int YKN_Push_UpdateLock(Nullable<int> @lock, string userID, string employeeID)
        {
            var lockParameter = @lock.HasValue ?
                new ObjectParameter("Lock", @lock) :
                new ObjectParameter("Lock", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("employeeID", employeeID) :
                new ObjectParameter("employeeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_UpdateLock", lockParameter, userIDParameter, employeeIDParameter);
        }
    
        public virtual int YKN_Push_UpdatePassword(string password, string userID, Nullable<System.DateTime> lastupdate)
        {
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var lastupdateParameter = lastupdate.HasValue ?
                new ObjectParameter("lastupdate", lastupdate) :
                new ObjectParameter("lastupdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_UpdatePassword", passwordParameter, userIDParameter, lastupdateParameter);
        }
    
        public virtual int YKN_Push_UpdatePeriod(Nullable<int> period, string userID)
        {
            var periodParameter = period.HasValue ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(int));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("YKN_Push_UpdatePeriod", periodParameter, userIDParameter);
        }
    }
}
