//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IDH.Sales.BLL.UserServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class UserWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetUserDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserDataByGuidOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePeriodOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateLockOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePasswordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserWebService() {
            this.Url = global::IDH.Sales.BLL.Properties.Settings.Default.IDH_Sales_BLL_UserServiceReference_UserWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetUserDataCompletedEventHandler GetUserDataCompleted;
        
        /// <remarks/>
        public event GetUserDataByGuidCompletedEventHandler GetUserDataByGuidCompleted;
        
        /// <remarks/>
        public event UpdatePeriodCompletedEventHandler UpdatePeriodCompleted;
        
        /// <remarks/>
        public event UpdateLockCompletedEventHandler UpdateLockCompleted;
        
        /// <remarks/>
        public event UpdatePasswordCompletedEventHandler UpdatePasswordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKN_P_GetUserData_Result GetUserData(string _UserName, string _Password, int _CompanyID) {
            object[] results = this.Invoke("GetUserData", new object[] {
                        _UserName,
                        _Password,
                        _CompanyID});
            return ((YKN_P_GetUserData_Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserDataAsync(string _UserName, string _Password, int _CompanyID) {
            this.GetUserDataAsync(_UserName, _Password, _CompanyID, null);
        }
        
        /// <remarks/>
        public void GetUserDataAsync(string _UserName, string _Password, int _CompanyID, object userState) {
            if ((this.GetUserDataOperationCompleted == null)) {
                this.GetUserDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserDataOperationCompleted);
            }
            this.InvokeAsync("GetUserData", new object[] {
                        _UserName,
                        _Password,
                        _CompanyID}, this.GetUserDataOperationCompleted, userState);
        }
        
        private void OnGetUserDataOperationCompleted(object arg) {
            if ((this.GetUserDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserDataCompleted(this, new GetUserDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserDataByGuid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public YKN_P_GetUserDataGUID_Result GetUserDataByGuid(string _UserGuid) {
            object[] results = this.Invoke("GetUserDataByGuid", new object[] {
                        _UserGuid});
            return ((YKN_P_GetUserDataGUID_Result)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserDataByGuidAsync(string _UserGuid) {
            this.GetUserDataByGuidAsync(_UserGuid, null);
        }
        
        /// <remarks/>
        public void GetUserDataByGuidAsync(string _UserGuid, object userState) {
            if ((this.GetUserDataByGuidOperationCompleted == null)) {
                this.GetUserDataByGuidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserDataByGuidOperationCompleted);
            }
            this.InvokeAsync("GetUserDataByGuid", new object[] {
                        _UserGuid}, this.GetUserDataByGuidOperationCompleted, userState);
        }
        
        private void OnGetUserDataByGuidOperationCompleted(object arg) {
            if ((this.GetUserDataByGuidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserDataByGuidCompleted(this, new GetUserDataByGuidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePeriod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdatePeriod(int Priod, string _UserGuid) {
            this.Invoke("UpdatePeriod", new object[] {
                        Priod,
                        _UserGuid});
        }
        
        /// <remarks/>
        public void UpdatePeriodAsync(int Priod, string _UserGuid) {
            this.UpdatePeriodAsync(Priod, _UserGuid, null);
        }
        
        /// <remarks/>
        public void UpdatePeriodAsync(int Priod, string _UserGuid, object userState) {
            if ((this.UpdatePeriodOperationCompleted == null)) {
                this.UpdatePeriodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePeriodOperationCompleted);
            }
            this.InvokeAsync("UpdatePeriod", new object[] {
                        Priod,
                        _UserGuid}, this.UpdatePeriodOperationCompleted, userState);
        }
        
        private void OnUpdatePeriodOperationCompleted(object arg) {
            if ((this.UpdatePeriodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePeriodCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateLock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateLock(int Lock, string _UserGuid, string employeeID) {
            this.Invoke("UpdateLock", new object[] {
                        Lock,
                        _UserGuid,
                        employeeID});
        }
        
        /// <remarks/>
        public void UpdateLockAsync(int Lock, string _UserGuid, string employeeID) {
            this.UpdateLockAsync(Lock, _UserGuid, employeeID, null);
        }
        
        /// <remarks/>
        public void UpdateLockAsync(int Lock, string _UserGuid, string employeeID, object userState) {
            if ((this.UpdateLockOperationCompleted == null)) {
                this.UpdateLockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateLockOperationCompleted);
            }
            this.InvokeAsync("UpdateLock", new object[] {
                        Lock,
                        _UserGuid,
                        employeeID}, this.UpdateLockOperationCompleted, userState);
        }
        
        private void OnUpdateLockOperationCompleted(object arg) {
            if ((this.UpdateLockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateLockCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdatePassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdatePassword(string Password, string _UserGuid, System.DateTime LastUpdate) {
            this.Invoke("UpdatePassword", new object[] {
                        Password,
                        _UserGuid,
                        LastUpdate});
        }
        
        /// <remarks/>
        public void UpdatePasswordAsync(string Password, string _UserGuid, System.DateTime LastUpdate) {
            this.UpdatePasswordAsync(Password, _UserGuid, LastUpdate, null);
        }
        
        /// <remarks/>
        public void UpdatePasswordAsync(string Password, string _UserGuid, System.DateTime LastUpdate, object userState) {
            if ((this.UpdatePasswordOperationCompleted == null)) {
                this.UpdatePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePasswordOperationCompleted);
            }
            this.InvokeAsync("UpdatePassword", new object[] {
                        Password,
                        _UserGuid,
                        LastUpdate}, this.UpdatePasswordOperationCompleted, userState);
        }
        
        private void OnUpdatePasswordOperationCompleted(object arg) {
            if ((this.UpdatePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePasswordCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKN_P_GetUserData_Result {
        
        private string fullNameField;
        
        private System.Guid userGUIDField;
        
        private string emailField;
        
        private string imageURLField;
        
        private string passwordField;
        
        private System.Guid ruleGUIDField;
        
        private System.Nullable<int> ruleNameField;
        
        private System.Nullable<System.Guid> managerGUIDField;
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid UserGUID {
            get {
                return this.userGUIDField;
            }
            set {
                this.userGUIDField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string ImageURL {
            get {
                return this.imageURLField;
            }
            set {
                this.imageURLField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RuleGUID {
            get {
                return this.ruleGUIDField;
            }
            set {
                this.ruleGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RuleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> ManagerGUID {
            get {
                return this.managerGUIDField;
            }
            set {
                this.managerGUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class YKN_P_GetUserDataGUID_Result {
        
        private string fullNameField;
        
        private System.Guid userGUIDField;
        
        private string emailField;
        
        private string imageURLField;
        
        private string passwordField;
        
        private System.Guid ruleGUIDField;
        
        private System.Nullable<int> ruleNameField;
        
        private System.Nullable<System.Guid> managerGUIDField;
        
        private string managernameField;
        
        private System.Nullable<int> lockField;
        
        /// <remarks/>
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid UserGUID {
            get {
                return this.userGUIDField;
            }
            set {
                this.userGUIDField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string ImageURL {
            get {
                return this.imageURLField;
            }
            set {
                this.imageURLField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid RuleGUID {
            get {
                return this.ruleGUIDField;
            }
            set {
                this.ruleGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> RuleName {
            get {
                return this.ruleNameField;
            }
            set {
                this.ruleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.Guid> ManagerGUID {
            get {
                return this.managerGUIDField;
            }
            set {
                this.managerGUIDField = value;
            }
        }
        
        /// <remarks/>
        public string Managername {
            get {
                return this.managernameField;
            }
            set {
                this.managernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Lock {
            get {
                return this.lockField;
            }
            set {
                this.lockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetUserDataCompletedEventHandler(object sender, GetUserDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKN_P_GetUserData_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKN_P_GetUserData_Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetUserDataByGuidCompletedEventHandler(object sender, GetUserDataByGuidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserDataByGuidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserDataByGuidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public YKN_P_GetUserDataGUID_Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((YKN_P_GetUserDataGUID_Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdatePeriodCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdateLockCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UpdatePasswordCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591